// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJRN7uy8_c3Azq7_29J3DTQ74Y6QDRSvA',
    appId: '1:1091344920359:web:7dcdf2dd37c56ef0c60302',
    messagingSenderId: '1091344920359',
    projectId: 'hackathon-a1670',
    authDomain: 'hackathon-a1670.firebaseapp.com',
    storageBucket: 'hackathon-a1670.appspot.com',
    measurementId: 'G-XGMKGPB1EK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXvso4fZto062c_5_T6F7sZuA76rRCxg8',
    appId: '1:1091344920359:android:55c4b704730fb883c60302',
    messagingSenderId: '1091344920359',
    projectId: 'hackathon-a1670',
    storageBucket: 'hackathon-a1670.appspot.com',
  );
}
